name: Download Kindle Source
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract
        run: |
          wget -q "https://kindle.s3.amazonaws.com/Kindle_src_5.6.5_2730300038.tar.gz"
          tar xzf Kindle_src_5.6.5_2730300038.tar.gz

      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Kindle GPL source extracted"
          git push
