name: Download Kindle Source
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and extract
        run: |
          wget -q "https://kindle.s3.amazonaws.com/Kindle_src_5.6.5_2730300038.tar.gz"
          tar xzf Kindle_src_5.6.5_2730300038.tar.gz
          rm Kindle_src_5.6.5_2730300038.tar.gz
          cd gplrelease
          tar xzf linux-3.0.35.tar.gz 
          rm linux-3.0.35.tar.gz 
          tar xzf build_linaro-gcc_4.8.3.tar.gz
          rm build_linaro-gcc_4.8.3.tar.gz
          tar xzf gcc-linaro-4.8-2014.04.tar.gz
          rm gcc-linaro-4.8-2014.04.tar.gz

      - name: Commit
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add .
          git commit -m "Kindle GPL source extracted"
          git push
